cc_binary(
    name = "demo",
    srcs = ["demo.cpp",],
    deps = [
        "//:cppjieba",
    ],
)

cc_binary(
    name = "load_test",
    srcs = ["load_test.cpp",],
    deps = [
        "//:cppjieba",
    ],
    )
